### ISSUE TITLE
Student emails should be able to show/hide the score

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#109]
We have show/hide numeric score
![image](https://user-images.githubusercontent.com/1979690/78265293-e0622b80-74c9-11ea-9ebf-2a4bf7b560eb.png)
![image](https://user-images.githubusercontent.com/1979690/78265314-e526df80-74c9-11ea-8b2e-8a33c8d712c2.png)

vs

![image](https://user-images.githubusercontent.com/1979690/78265339-eb1cc080-74c9-11ea-8156-7671a5c174c8.png)
![image](https://user-images.githubusercontent.com/1979690/78265358-f07a0b00-74c9-11ea-908c-4afedb2374a1.png)

Users would like a way to show/hide the score on the student's email reports, too. Since show/hide is a display-only option and not actually a configuration of the Rubric, it is not immediately clear how to provide this choice to the Teacher. Perhaps we should put a checkbox near the Email button?
![image](https://user-images.githubusercontent.com/1979690/78265536-2fa85c00-74ca-11ea-8559-b22975300514.png)

**Comment by JackyBreak** [comment]
![image](https://user-images.githubusercontent.com/42852377/78315668-4dee7600-7523-11ea-9a36-72d45f786e8b.png)

![image](https://user-images.githubusercontent.com/42852377/78315661-475ffe80-7523-11ea-9303-967798b5c18e.png)
