### ISSUE TITLE
Project debrief

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#126]
To make sure we can continue to make changes after you are done, consider the following.

## Code
- [ ] reduce duplicated code
- [ ] extract code into more than 1 py file
- [ ] refactor functions that are very long
- [ ] delete unused/outdated files or code
- [ ] add comments; priority is one comment summarizing each function
- [ ] rename important variables/functions/etc to be more descriptive or accurate

## Documentation (can go in the [wiki](https://github.com/sotl-technology/rubricapp/wiki))

- [ ] document how certain aspects of the app work, such as the login sessions
- [ ] document examples of how you make different kinds of changes to the app: e.g., UI change, change to spreadsheet schema or interaction, change to DB schema or interaction
- [ ] document what the data storage model is - user directory structure, what data is in spreadsheets, what data is in DB
- [ ] document what pages are accessible and not accessible, known accessibility issues, etc

**Comment by JackyBreak** [comment]
1. Move out the database part into a separate .py file

**Comment by JackyBreak** [comment]
2. Login code
3. Helper function

**Comment by bellqueen** [comment]
2. Move out all helper function using for Excel

**Comment by JackyBreak** [comment]
4. Code which associates with excel sheet
5. Create interfaces of modifying database

**Comment by JackyBreak** [comment]
Add a readme file in the templates folder and explain the orientation of each html template
