### ISSUE TITLE
email reliable and working OR student reports

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#55]
In GitLab by @bmyerz on Jan 9, 2020, 21:48

Getting the emails to send again and to work for the PDF or HTML to look legible.

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Feb 6, 2020, 13:40

changed title from **{-CRITICAL: email reliable and working-}** to **{+email reliable and working OR student reports+}**

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Feb 6, 2020, 13:40

changed the description

**Comment by bmyerz** [comment]
Emails not currently being sent on prod server

@bellqueen needs access to a linux debugging environment to work on email sending

**Comment by bmyerz** [comment]
Email is now working with 3 emails, but test with many students using mailinator.com email addresses.

**Comment by JackyBreak** [comment]
Record how long it takes to receive the emails

**Comment by bmyerz** [comment]
if an email is unreachable, then do something useful with the error message
