### ISSUE TITLE
Making sure the sharing / multiple raters works clearly

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#56]
In GitLab by @bmyerz on Jan 9, 2020, 21:51

Not a new feature.

Test existing sharing of 1 instructor and 2 TAs. Also create instructions for how teacher creates and shares the project

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Jan 9, 2020, 21:52

changed the description

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Jan 27, 2020, 20:49

~Jan10: our users Suzanne and Gil found that this feature did not work for them

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Feb 6, 2020, 13:39

changed title from **{-CRITICAL: -}Making sure the sharing / multiple raters works clearly** to **Making sure the sharing / multiple raters works clearly**

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Feb 6, 2020, 13:39

changed the description

**Comment by bmyerz** [comment]
@bellqueen 
I've tested sharing a project using
![image](https://user-images.githubusercontent.com/1979690/74371410-66050d00-4d9e-11ea-8e4d-799f244c3e0d.png)
on Profile / Manage

It seems to succeed in updating the permissions
![image](https://user-images.githubusercontent.com/1979690/74371449-761cec80-4d9e-11ea-8f2d-da1705c666a1.png)

And the other user can see the project in shared
![image](https://user-images.githubusercontent.com/1979690/74371506-8af98000-4d9e-11ea-8ede-4c6150e6c3e5.png)

And I can get to the evaluations.

![image](https://user-images.githubusercontent.com/1979690/74371597-b0868980-4d9e-11ea-9aba-4d723c5d2599.png)

 However, clicking a meta group gives a server error.

However, clicking on the project here causes a server error. Log says

File "{base directory redacted}/app.py", line 1111, in jump_to_evaluation_page
evaluation_workbook = openpyxl.load_workbook(path_to_evaluation_file)
...
FileNotFoundError: [Errno 2] No such file or directory: '{base directory redacted}/sampleuser3b/GilsClass3/evaluation.xlsx'

Indeed the code is looking for a folder for that project but it is using the wrong user name. It should use the name of the sharer but it is using the name of the shared-to person.

**Comment by bmyerz** [comment]
Interestingly, in jump_to_evaluation_page, it says correctly that 

project.owner sampleuser3             (this is the sharer)

**Comment by bmyerz** [comment]
crashing after changing the permissions, fixing with 
https://github.com/sotl-technology/rubricapp/commit/9c17f27359f2f45f8a6adbae9d0c8671900f8fb8

**Comment by bmyerz** [comment]
branch making some bug fixes https://github.com/sotl-technology/rubricapp/tree/issue56

**Comment by bmyerz** [comment]
After b238a5f and 9c17f27 are in, I am able to have the shared-to user access the grading pages. And both users are to some extent able to make edits to the grades.

However, there are non-determinism errors. I think this is concurrency (file locking) related, but we should also keep in mind #59 .

**Comment by bellqueen** [comment]
1. Save grade : remove edit | only support overwrite  |  give a sign that the grade is successfully saved
2. Share permission : Make sure the permission is successfully granted  |  let the owner see which users they share rubric to.

**Comment by bellqueen** [comment]
* Removing the update and overwrite button and only using save

**Comment by bmyerz** [comment]
It looks like  b238a5f and 9c17f27 were not included in the related pull request.
- [ ] test if they were fixed or not before resolving this issue

**Comment by bmyerz** [comment]
As of today's master, the saving behavior is better but still buggy
- [ ] creates a new tab each time you switch
![image](https://user-images.githubusercontent.com/1979690/75178584-fb3cc580-56fd-11ea-9bd8-2911765f02d5.png)
![image](https://user-images.githubusercontent.com/1979690/75178603-02fc6a00-56fe-11ea-80ac-7e68d5eb251b.png)
![image](https://user-images.githubusercontent.com/1979690/75178615-08f24b00-56fe-11ea-894f-4739a6bf6f28.png)
![image](https://user-images.githubusercontent.com/1979690/75178634-10195900-56fe-11ea-85a5-70210d4968c7.png)
![image](https://user-images.githubusercontent.com/1979690/75178654-1d364800-56fe-11ea-9c88-8447aa3368c4.png)
![image](https://user-images.githubusercontent.com/1979690/75178670-26bfb000-56fe-11ea-9522-f74591854754.png)



- [ ] non-deterministically still doesn't save the grade sometimes? Needs to be tested more rigorously

**Comment by bmyerz** [comment]
closing in favor of #59 and #85
