### ISSUE TITLE
Increase character limit for project name

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#60]
In GitLab by @bmyerz on Jan 27, 2020, 20:56

Currently too short to fit words like "Information Processing"

**Comment by bmyerz** [comment]
In GitLab by @JackyBreak on Feb 3, 2020, 16:02

Modified the upper limit to 50 characters long, added requirement info in description. Unable to add event-listener to display current length of input due to hidden tags.

**Comment by bellqueen** [comment]
fixed in merge:
Runqzhao #86
