### ISSUE TITLE
Make the rubric copying more obvious

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#65]
In GitLab by @bmyerz on Feb 6, 2020, 14:23

Currently hidden inside account page with an unnamed search bar.
![image](/uploads/716af02156642e27dbe9a4dce23b3d95/image.png)

Suggest delete all other info on Account page
![image](/uploads/f499810d1b3b4af1e3b8030e10c5711f/image.png)
Label search bar with "search for user who's rubric you want to copy".
![image](/uploads/ffa2657b3555c155d78e6911554bf6f9/image.png)

 and rename tab from Account to Copy Rubric. 
![image](/uploads/3aabf458d8e54b5e21b2213450acfc0e/image.png)

Change Share! to Copy
![image](/uploads/160abe0ea57e745487d956dd5089c947/image.png)

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Feb 6, 2020, 14:25

changed the description

**Comment by bmyerz** [comment]
In GitLab by @bmyerz on Feb 6, 2020, 14:26

changed the description

**Comment by bmyerz** [comment]
project update - @JackyBreak has this basically working but still need to get the new way of searching for projects by name to properly create a new project

**Comment by JackyBreak** [comment]
need to be closed
