### ISSUE TITLE
Long project names are silently truncated

### ISSUE THREAD

**Issue by bmyerz** [sotl-technology/rubricapp#80]
to reproduce, you'll see project name
CHEM300 S00 Information Processing

Leads to truncation. The folder on the server has the full name, but the project name in the sql database gets truncated to "CHEM300 S00 Information Proces". This mismatch causes errors when you try to match the folder name to the database's name for the project, such as when you click the Profile page (project_profile_jumptool).

**Comment by bellqueen** [comment]
The size of project name in database mismatch the size limit in html

**Comment by bmyerz** [comment]
project update on 2/19/2020 - progress has been made but we needed to 
* remove the database file (for sqlite)
* change the table schema in mysql (for rubric-dev server)
https://stackoverflow.com/questions/22668024/how-to-change-column-size-of-varchar-type-in-mysql

**Comment by bellqueen** [comment]
How to modify column size:
example 
MariaDB [rubric]> alter table notification modify from_user varchar(30);

**Comment by bellqueen** [comment]
alter table permission modify project_id varchar(255);
alter table permission modify owner varchar(30);
alter table permission modify shareTo varchar(30);
alter table permission modify project varchar(150);
alter table permission modify status varchar(50);

alter table user modify username varchar(30);
alter table user modify email varchar(255);
alter table user modify role varchar(20);
alter table user modify University varchar(255);
alter table project modify project_name varchar(150);
alter table project modify owner varchar(30);
alter table project modify project_status varchar(50);
alter table evaluation modify eva_name varchar(150);
alter table evaluation modify project_name varchar(150);
alter table evaluation modify project_owner varchar(30);
alter table evaluation modify owner varchar(30);
alter table evaluation modify last_edit varchar(15);
alter table evaluation modify last_edit varchar(30);
alter table notification modify from_user varchar(30);
alter table notification modify to_user varchar(30);

**Comment by bellqueen** [comment]
make every column to 255

**Comment by bmyerz** [comment]
completed the alter commands in rubric.cs server
